name: netset_ai
description: An AI base chat bot application in flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  carousel_slider: ^4.2.1
  get: ^4.6.5
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.1
  lottie: ^2.3.2
  speech_to_text: ^6.1.1
  flutter_dotenv: ^5.1.0
  flutter_tts: ^3.7.0
  flutter_launcher_icons: ^0.13.1
  google_sign_in: ^6.1.4
  dio: ^5.2.1+1
  get_it: ^7.2.0
  permission_handler: ^10.3.0
  image_gallery_saver: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21

flutter:
  fonts:
    - family: bold
      fonts:
        - asset: assets/fonts/bold.ttf
    - family: medium
      fonts:
        - asset: assets/fonts/medium.ttf
    - family: regular
      fonts:
        - asset: assets/fonts/regular.ttf


  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
    - lib/.env

